name: Deploy Library System

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DevOps repository
        uses: actions/checkout@v2
        with:
          path: library-devops

      - name: Checkout Frontend repository
        uses: actions/checkout@v2
        with:
          repository: library-system-devops/library-frontend
          path: library-frontend
          token: ${{ secrets.GH_PAT }}

      - name: Checkout Backend repository
        uses: actions/checkout@v2
        with:
          repository: library-system-devops/library-backend
          path: library-backend
          token: ${{ secrets.GH_PAT }}

      - name: Setup Directory Structure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            rm -rf ~/library-system/*
            mkdir -p ~/library-system/frontend/src
            mkdir -p ~/library-system/backend/src

      - name: Copy Frontend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          source: "library-frontend/*"
          target: "/home/${{ secrets.GCP_SSH_USERNAME }}/library-system/frontend/"
          strip_components: 1

      - name: Copy Backend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          source: "library-backend/*"
          target: "/home/${{ secrets.GCP_SSH_USERNAME }}/library-system/backend/"
          strip_components: 1

      - name: Copy Docker and Config files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          source: "library-devops/docker-compose.yml"
          target: "/home/${{ secrets.GCP_SSH_USERNAME }}/library-system/"
          strip_components: 1

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd ~/library-system
            
            # Setup environment
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> .env
            
            # Ensure docker is running
            sudo service docker start
            
            # Clean up existing resources
            docker-compose down -v
            
            # Start services
            docker-compose up -d --build

      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd ~/library-system
            echo "Docker Containers:"
            docker ps
            echo "\nDocker Networks:"
            docker network ls
            echo "\nDocker Volumes:"
            docker volume ls
            echo "\nDirectory Structure:"
            ls -R
            echo "\nDocker Compose Logs:"
            docker-compose logs